#!/usr/bin/env python3
"""
Unamused Fix Kit generator v0.1.
Usage: python3 fixkit.py <url> [--out dir]

Runs the audit, then generates a personalized fix kit for everything the site
failed or warned on:
  README.md            personalized install steps
  llms.txt             curated from a real crawl of the site's key pages
  schema-jsonld.html   JSON-LD LocalBusiness-family markup, pre-filled
  robots.txt           only if missing or site-wide blocking
  og-tags.html         only if Open Graph tags missing
  guides/              wordpress.md, wix.md, squarespace.md, shopify.md, generic.md

Output: fixkit-<slug>-<stamp>.zip
"""
import json
import os
import re
import sys
import urllib.parse
import zipfile
from datetime import datetime, timezone
from html.parser import HTMLParser

import audit

GUIDE_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                         "fixkit", "guides")

# Attribution: every generated file carries a credit line. SITE_URL is set in
# production so credits link back to the hosted service.
SITE_URL = os.environ.get("SITE_URL", "").rstrip("/")


def credit_line():
    base = "Generated by Unamused — free, open-source agent-readiness audit"
    return base + (" <%s>" % SITE_URL if SITE_URL else "")


def html_credit():
    return "<!-- %s -->\n" % credit_line()

TYPE_KEYWORDS = [
    ("Restaurant", ["restaurant", "menu", "pizza", "cuisine", "chef", "dining",
                    "reservations", "takeout", "delivery"]),
    ("Dentist", ["dentist", "dental", "teeth", "orthodont", "cleaning", "cavity"]),
    ("Store", ["cart", "checkout", "add to cart", "products", "shop online"]),
    ("Hotel", ["hotel", "rooms", "suites", "check-in", "lodging"]),
    ("MedicalClinic", ["clinic", "doctor", "physician", "patients", "appointment"]),
]


class TextExtractor(HTMLParser):
    def __init__(self):
        super().__init__(convert_charrefs=True)
        self.parts = []
        self._skip = 0

    def handle_starttag(self, tag, attrs):
        if tag in ("script", "style", "nav", "footer", "noscript"):
            self._skip += 1

    def handle_endtag(self, tag):
        if tag in ("script", "style", "nav", "footer", "noscript") and self._skip:
            self._skip -= 1

    def handle_data(self, data):
        if not self._skip:
            t = data.strip()
            if t:
                self.parts.append(t)

    def text(self, limit=2000):
        return re.sub(r"\s+", " ", " ".join(self.parts))[:limit]


def page_text(html):
    e = TextExtractor()
    try:
        e.feed(html[:500_000])
    except Exception:
        pass
    return e.text()


def detect_type(text):
    low = text.lower()
    best, best_n = "LocalBusiness", 0
    for t, kws in TYPE_KEYWORDS:
        n = sum(low.count(k) for k in kws)
        if n > best_n:
            best, best_n = t, n
    return best


def clean_name(title):
    title = (title or "").strip()
    for sep in [" | ", " - ", " – ", " — "]:
        if sep in title:
            title = title.split(sep)[0]
    return title.strip()[:80]


def org_name_from_ld(blobs):
    """Business name from the site's own JSON-LD Organization/LocalBusiness markup,
    when present. More accurate than the <title> tag (which is often SEO copy)."""
    def pick(items):
        for it in items:
            if not isinstance(it, dict):
                continue
            t = it.get("@type", "")
            types = t if isinstance(t, list) else [t]
            if any(x in ("Organization", "LocalBusiness", "Corporation",
                         "Company", "Brand") for x in types):
                n = (it.get("name") or "").strip()
                if n:
                    return n[:80]
            graph = it.get("@graph")
            if isinstance(graph, list):
                n = pick(graph)
                if n:
                    return n
        return ""

    for blob in blobs:
        try:
            d = json.loads(blob)
        except Exception:
            continue
        n = pick(d if isinstance(d, list) else [d])
        if n:
            return n
    return ""


def crawl_key_pages(base, homepage_html, parser, limit=8):
    """Same-domain nav links with the best anchor text."""
    seen, pages = set(), []
    for href, text in parser.anchors:
        if not href or not text:
            continue
        full = urllib.parse.urljoin(base + "/", href)
        u = urllib.parse.urlparse(full)
        b = urllib.parse.urlparse(base)
        if u.netloc != b.netloc or u.scheme not in ("http", "https"):
            continue
        if full in seen or u.path in ("", "/"):
            continue
        if len(text.strip()) < 3 or len(pages) >= limit:
            continue
        seen.add(full)
        r = audit.fetch(full)
        if not r["ok"]:
            continue
        p2 = audit.PageParser()
        try:
            p2.feed(r["body"][:500_000])
        except Exception:
            pass
        pages.append({"url": full, "title": clean_name(p2.title) or text.strip()[:60],
                      "desc": (p2.metas.get("description") or
                               page_text(r["body"])[:160]).strip()})
    return pages


def build_llms_txt(name, desc, base, key_pages, contact):
    lines = ["# %s" % credit_line(), "", "# %s" % name, ""]
    if desc:
        lines += ["> %s" % desc, ""]
    lines += ["## Key pages", ""]
    lines.append("- [Home](%s/): %s" % (base.rstrip("/"), desc or name))
    for pg in key_pages:
        lines.append("- [%s](%s): %s" % (pg["title"], pg["url"], pg["desc"]))
    lines += ["", "## Contact", ""]
    for k, v in contact.items():
        if v:
            lines.append("- %s: %s" % (k, v))
    lines += ["", "_%s. Keep curated: link the pages "
              "that answer customer questions, not everything._" % credit_line(), ""]
    return "\n".join(lines)


def build_schema(biz_type, name, desc, url, tel, address, hours):
    data = {"@context": "https://schema.org", "@type": biz_type,
            "name": name, "url": url}
    if desc:
        data["description"] = desc[:300]
    if tel:
        data["telephone"] = tel
    if address and not address.startswith("["):
        data["address"] = {"@type": "PostalAddress", "streetAddress": address}
    elif address:
        data["address"] = {"@type": "PostalAddress",
                           "streetAddress": "REPLACE_WITH_STREET_ADDRESS"}
    if hours and not hours.startswith("["):
        data["openingHours"] = hours
    snippet = (html_credit() +
               "<!-- Paste this into the <head> of every page, then replace any "
               "REPLACE_WITH_ placeholders. -->\n"
               '<script type="application/ld+json">\n%s\n</script>\n'
               % json.dumps(data, indent=2))
    return snippet


def build_robots(base, existing):
    return ("# %s\n" % credit_line() +
            "User-agent: *\nAllow: /\n\n"
            "# AI agents and crawlers are welcome here.\n"
            "Sitemap: %s/sitemap.xml\n" % base.rstrip("/"))


def build_og(name, desc, url):
    return (html_credit() +
            """<!-- Paste into <head>. Upload an og-image.jpg (1200x630) to your site root first. -->
<meta property="og:title" content="%s">
<meta property="og:description" content="%s">
<meta property="og:image" content="%s/og-image.jpg">
<meta property="og:url" content="%s">
<meta property="og:type" content="website">
""" % (name, (desc or name)[:200], url.rstrip("/"), url))


def load_guide(name):
    path = os.path.join(GUIDE_DIR, name + ".md")
    try:
        with open(path) as f:
            return f.read()
    except Exception:
        return None


def generate(url, out_dir="."):
    rep = audit.audit(url)
    if rep.get("error"):
        raise RuntimeError("Audit failed: %s" % rep["error"])
    base = "%s://%s" % tuple(urllib.parse.urlparse(rep["final_url"])[:2])
    page = audit.fetch(rep["final_url"])
    parser = audit.PageParser()
    try:
        parser.feed(page["body"][:2_000_000])
    except Exception:
        pass

    text = page_text(page["body"])
    name = (org_name_from_ld(parser.ld_json)
            or clean_name(parser.title)
            or urllib.parse.urlparse(base).netloc)
    desc = parser.metas.get("description", "")[:300]
    tel = next((h[4:] for h, _ in parser.anchors if h.startswith("tel:")), "")
    biz_type = detect_type(text)

    # reuse existing schema fields when present
    address, hours = "[YOUR STREET, CITY, STATE ZIP]", "[e.g. Mo-Fr 09:00-17:00]"
    for blob in parser.ld_json:
        try:
            d = json.loads(blob)
        except Exception:
            continue
        items = d if isinstance(d, list) else [d]
        for it in items:
            if isinstance(it, dict) and isinstance(it.get("address"), dict):
                sa = it["address"]
                address = ", ".join(x for x in
                                    [sa.get("streetAddress"), sa.get("addressLocality"),
                                     sa.get("addressRegion"), sa.get("postalCode")] if x)
            if isinstance(it, dict) and it.get("openingHours"):
                oh = it["openingHours"]
                hours = ", ".join(oh) if isinstance(oh, list) else str(oh)

    key_pages = crawl_key_pages(base, page["body"], parser)
    contact = {"Phone": tel, "Address": address, "Hours": hours}

    checks = {c["name"]: c for c in rep["checks"]}
    failed = lambda n: checks.get(n, {}).get("status") in ("fail", "warn")

    files = {}
    files["llms.txt"] = build_llms_txt(name, desc, base, key_pages, contact)
    files["schema-jsonld.html"] = build_schema(biz_type, name, desc,
                                              rep["final_url"], tel, address, hours)
    rb = audit.fetch(base + "/robots.txt")
    if not rb["ok"]:
        files["robots.txt"] = build_robots(base, None)
    elif "disallow: /" in rb["body"].lower().replace(" ", ""):
        files["robots-addendum.txt"] = (
            "# Your robots.txt currently blocks ALL crawlers (Disallow: /).\n"
            "# Remove that line so AI agents can read and recommend your site, "
            "then add:\n\n" + build_robots(base, None))
    if failed("Social/OG meta"):
        files["og-tags.html"] = build_og(name, desc, rep["final_url"])

    for g in ["wordpress", "wix", "squarespace", "shopify", "generic"]:
        content = load_guide(g)
        if content:
            files["guides/%s.md" % g] = content

    steps = [
        "1. Upload `llms.txt` to your website's root folder (same place as robots.txt).",
    ]
    if "schema-jsonld.html" in files:
        steps.append("2. Paste `schema-jsonld.html` into the <head> of every page "
                     "(see your platform's guide in guides/). Replace any REPLACE_WITH_ placeholders.")
    if "robots.txt" in files:
        steps.append("3. Upload `robots.txt` to your root folder (or merge the AI-friendly "
                     "lines into your existing one).")
    if "robots-addendum.txt" in files:
        steps.append("3. URGENT: your robots.txt blocks all crawlers — follow robots-addendum.txt first.")
    if "og-tags.html" in files:
        steps.append("4. Paste `og-tags.html` into <head> and upload a 1200x630 og-image.jpg.")
    steps.append("%d. Re-run the free audit at https://unamused.app when done — at "
                 "85+/100 you earn the Amused badge." % (len(steps) + 1))

    files["README.md"] = (
        "# Your Unamused Fix Kit\n\n"
        "Site: %s\nAudit score: %d/100 (%s)\nGenerated: %s\n\n"
        "## What we found\n\n" % (rep["url"], rep["score"], rep["grade"],
                                  datetime.now(timezone.utc).strftime("%Y-%m-%d")) +
        "".join("- [%s] %s: %s\n" % (c["status"].upper(), c["name"], c["detail"][:120])
                for c in rep["checks"] if c["status"] != "pass") +
        "\n## Install steps\n\n" + "\n".join(steps) + "\n\n"
        "## Files in this kit\n\n" +
        "".join("- `%s`\n" % f for f in sorted(files) if f != "README.md") +
        "\n_Stuck? Everything is free and open source — open an issue at "\
        "https://github.com/DPL1979/unamused._\n")

    slug = re.sub(r"[^a-z0-9]+", "-", urllib.parse.urlparse(base).netloc.lower()).strip("-")
    stamp = datetime.now(timezone.utc).strftime("%Y%m%d")
    zipname = os.path.join(out_dir, "fixkit-%s-%s.zip" % (slug, stamp))
    with zipfile.ZipFile(zipname, "w", zipfile.ZIP_DEFLATED) as z:
        for fname, content in files.items():
            z.writestr("unamused-fixkit/" + fname, content)
    print("Score was %d/100 — kit covers %d failed/warned checks."
          % (rep["score"], sum(1 for c in rep["checks"] if c["status"] != "pass")))
    print("Wrote %s (%d files)" % (zipname, len(files)))
    return zipname


if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("usage: python3 fixkit.py <url> [--out dir]")
        sys.exit(1)
    url = sys.argv[1]
    out = sys.argv[sys.argv.index("--out") + 1] if "--out" in sys.argv else "."
    os.makedirs(out, exist_ok=True)
    generate(url, out)
