#!/usr/bin/env python3
"""End-to-end test of the Unamused site (renamed). Monkeypatches network fetch."""
import io
import json
import os
import sys
import zipfile

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import audit as engine
import app as webapp

FIXTURE = """<!DOCTYPE html><html lang="en"><head>
<title>Mario &amp; Salvo's Pizzeria — Brooklyn, NY</title>
<meta name="description" content="Family pizzeria in Brooklyn.">
<meta property="og:title" content="Mario & Salvo's">
<meta property="og:description" content="Best pizza in Brooklyn">
<meta property="og:image" content="https://example.com/pie.jpg">
<meta name="viewport" content="width=device-width, initial-scale=1">
<script type="application/ld+json">
{"@context":"https://schema.org","@type":"Restaurant","name":"Mario & Salvo's Pizzeria",
"telephone":"+1-718-555-0100",
"address":{"@type":"PostalAddress","streetAddress":"123 Grand St","addressLocality":"Brooklyn","addressRegion":"NY","postalCode":"11249"},
"openingHours":"Mo-Su 11:00-23:00","servesCuisine":"Pizza"}
</script></head>
<body><header><h1>Mario &amp; Salvo's</h1></header>
<main><p>Call <a href="tel:+17185550100">718-555-0100</a> to order.</p>
<p>123 Grand St, Brooklyn NY 11249. Open daily 11am-11pm.</p>
<a href="https://example.com/order">Order online</a></main>
<footer><nav><a href="/menu">Menu</a></nav></footer></body></html>"""

def fake_fetch(url):
    return {"ok": True, "status": 200, "body": FIXTURE, "bytes": len(FIXTURE),
            "ms": 400, "final_url": url, "error": None}

engine.fetch = fake_fetch
webapp.is_public_host = lambda host: True


def main():
    c = webapp.app.test_client()
    fails = []
    def check(name, cond, extra=""):
        print(("PASS " if cond else "FAIL ") + name + (" " + extra if extra else ""))
        if not cond:
            fails.append(name)

    r = c.get("/")
    check("homepage 200", r.status_code == 200, str(r.status_code))
    check("homepage brand", b"Unamused" in r.data and b"Is Muse unamused" in r.data)
    check("no old brand on homepage", b"Muse Ready" not in r.data and b"MUSE READY" not in r.data)

    r = c.get("/fix")
    check("/fix gone (404)", r.status_code == 404, str(r.status_code))

    r = c.post("/audit", data={"url": "https://example.com"})
    check("audit redirects", r.status_code in (301, 302, 303), str(r.status_code))
    rid = r.headers["Location"].rstrip("/").split("/")[-1]

    r = c.get("/r/" + rid)
    check("report 200", r.status_code == 200, str(r.status_code))
    body = r.data.decode("utf-8", "replace")
    import re
    m = re.search(r'<div class="grade">([^<]+)</div>', body)
    grade = m.group(1) if m else "?"
    check("new grade shown", grade in ("Amused", "Almost amused", "Unamused", "Deeply unamused"), grade)
    gclass = "g-" + grade.replace(" ", "-").lower()
    check("grade CSS class wired", ('class="dial-fg %s"' % gclass) in body, gclass)
    check("kit link present", ("/kit/" + rid) in body)
    check("no old brand in report", "Muse Ready" not in body and "MUSE READY" not in body)

    r = c.get("/kit/" + rid)
    check("kit 200", r.status_code == 200, str(r.status_code))
    check("kit is zip", r.headers.get("Content-Type") == "application/zip", r.headers.get("Content-Type"))
    z = zipfile.ZipFile(io.BytesIO(r.data))
    names = z.namelist()
    check("kit prefixed unamused-fixkit/", all(n.startswith("unamused-fixkit/") for n in names), "%d files" % len(names))
    check("kit has core files", len(names) >= 5, str(len(names)))
    llms = z.read("unamused-fixkit/llms.txt").decode("utf-8", "replace")
    check("kit attribution", "Generated by Unamused" in llms)
    kit_all = "\n".join(z.read(n).decode("utf-8", "replace") for n in names)
    check("kit no old brand", "Muse Ready" not in kit_all and "MUSE READY" not in kit_all)

    r = c.get("/static/badge.svg")
    check("badge 200", r.status_code == 200, str(r.status_code))
    check("badge says AMUSED", b"AMUSED" in r.data and b"MUSE READY" not in r.data)

    home = c.get("/").data.decode("utf-8", "replace")
    paid_words = ["$299", "Concierge", "$29", "STRIPE_PAYMENT_LINK", "/fix",
                  "order email", "Fix Kit email", "your order"]
    check("no paid-tier remnants", not any(w in home for w in paid_words),
          str([w for w in paid_words if w in home]))
    check("kit no paid-tier remnants",
          not any(w in kit_all for w in paid_words),
          str([w for w in paid_words if w in kit_all]))

    r = c.get("/k/" + rid)
    check("kit page 200", r.status_code == 200, str(r.status_code))
    kp = r.data.decode("utf-8", "replace")
    check("kit page lists files", "llms.txt" in kp and "schema-jsonld.html" in kp)
    check("kit page has copy buttons",
          kp.count('class="copy-btn"') == kp.count('<pre id="kf') and kp.count('class="copy-btn"') >= 1,
          "%d buttons, %d pres" % (kp.count('class="copy-btn"'), kp.count('<pre id="kf')))
    check("kit page links zip", ("/kit/" + rid) in kp)

    r = c.get("/api")
    check("api docs 200", r.status_code == 200 and b"/api/v1/audit" in r.data,
          str(r.status_code))

    r = c.post("/api/v1/audit", json={"url": "https://example.com"})
    check("api audit 200 json", r.status_code == 200 and r.is_json, str(r.status_code))
    aj = r.get_json()
    check("api audit shape",
          aj.get("score") is not None and aj.get("report_url", "").endswith("/r/" + aj.get("report_url", "").rsplit("/", 1)[-1]),
          str(sorted(aj.keys())))
    check("api audit kit links",
          "/k/" in aj.get("kit_page_url", "") and "/kit/" in aj.get("kit_zip_url", ""))

    r = c.get("/api/v1/report/" + rid)
    check("api report 200 json", r.status_code == 200 and r.is_json, str(r.status_code))
    check("api report has checks", isinstance(r.get_json().get("checks"), list))

    r = c.get("/api/v1/kit/" + rid)
    check("api kit 200 json", r.status_code == 200 and r.is_json, str(r.status_code))
    kj = r.get_json()
    check("api kit has files",
          isinstance(kj.get("files"), dict) and "llms.txt" in kj["files"],
          str(sorted(kj.get("files", {}).keys())))

    r = c.post("/api/v1/audit", json={"url": "not a url"})
    check("api audit 400 on bad url", r.status_code == 400, str(r.status_code))

    # ---- Per-business Agent API ----
    import agentapi

    good, err = agentapi.validate_action({
        "name": "book_visit", "title": "Book a visit",
        "description": "Book a visit.",
        "params": [{"name": "name", "type": "string", "required": True,
                    "description": "Customer name"}],
        "channel": {"type": "link",
                    "url_template": "https://cal.example.com/x?name={name}"},
        "requires_approval": True})
    check("validate_action accepts link action", good is not None and err is None, str(err))

    bad, err = agentapi.validate_action({
        "name": "Bad Name!", "title": "x", "description": "x",
        "params": [{"name": "p", "type": "string", "required": False, "description": ""}],
        "channel": {"type": "link", "url_template": "https://x.example.com/"}})
    check("validate_action rejects bad name", bad is None and err is not None, str(err))

    bad2, err2 = agentapi.validate_action({
        "name": "ok_name", "title": "x", "description": "x",
        "params": [{"name": "phone", "type": "string", "required": False, "description": ""}],
        "channel": {"type": "webhook", "url": "https://localhost/hook"}})
    check("validate_action rejects private webhook", bad2 is None and err2 is not None, str(err2))

    ok, res = agentapi.execute_action(
        {"id": "t", "business": "Test Biz", "actions": [good]},
        "book_visit", {"name": "Jane Doe"})
    check("link channel fills template",
          ok and res.get("handoff_url") == "https://cal.example.com/x?name=Jane%20Doe",
          str(res))

    ok, res = agentapi.execute_action(
        {"id": "t", "business": "Test Biz", "actions": [good]},
        "book_visit", {})
    check("missing required param fails", not ok and "name" in res.get("error", ""), str(res))

    rec = agentapi.build_record("Test Biz", "https://example.com", [good])
    spec = agentapi.openapi_spec(rec, "https://unamused.app")
    check("openapi has action path",
          "/a/%s/actions/book_visit" % rec["id"] in spec["paths"], str(list(spec["paths"])))
    check("openapi marks approval",
          spec["paths"]["/a/%s/actions/book_visit" % rec["id"]]["post"].get(
              "x-unamused-requires-approval") is True)

    m = agentapi.connector_manifest(rec, "https://unamused.app")
    check("manifest has endpoints",
          m["openapi_url"].endswith("/openapi.json") and m["mcp_url"].endswith("/mcp"))

    r = agentapi.mcp_handle(rec, {"jsonrpc": "2.0", "id": 1, "method": "initialize"})
    check("mcp initialize", r["result"]["protocolVersion"] == agentapi.MCP_VERSION)
    r = agentapi.mcp_handle(rec, {"jsonrpc": "2.0", "id": 2, "method": "tools/list"})
    check("mcp tools/list",
          len(r["result"]["tools"]) == 1 and r["result"]["tools"][0]["name"] == "book_visit",
          str(r))
    check("mcp approval annotation",
          r["result"]["tools"][0].get("annotations", {}).get("destructiveHint") is True)
    r = agentapi.mcp_handle(rec, {"jsonrpc": "2.0", "id": 3, "method": "tools/call",
                                  "params": {"name": "book_visit",
                                             "arguments": {"name": "Jane"}}})
    check("mcp tools/call",
          not r["result"]["isError"] and "Jane" in r["result"]["content"][0]["text"],
          str(r["result"])[:200])
    r = agentapi.mcp_handle(rec, {"jsonrpc": "2.0", "id": 5, "method": "nope"})
    check("mcp unknown method", r["error"]["code"] == -32601)
    check("mcp notification -> None",
          agentapi.mcp_handle(rec, {"jsonrpc": "2.0",
                                    "method": "notifications/initialized"}) is None)

    # routes: builder -> create -> page -> spec -> manifest -> mcp -> action
    r = c.get("/a/new/" + rid)
    check("agent builder 200", r.status_code == 200 and b"Agent API" in r.data,
          str(r.status_code))
    r = c.get("/a/new/nonexistent12")
    check("agent builder 404 on bad rid", r.status_code == 404, str(r.status_code))

    form = {
        "business": "Mario & Salvo's Pizzeria", "url": "https://example.com",
        "action_name": "book_table", "action_title": "Book a table",
        "action_desc": "Book a table at the pizzeria.",
        "action_channel_0": "link", "action_link_0": "https://book.example.com/?name={name}",
        "action_approval_0": "on",
        "action_pname_0_0": "name", "action_ptype_0_0": "string",
        "action_preq_0_0": "on", "action_pdesc_0_0": "Customer name",
        "action_pname_0_1": "party_size", "action_ptype_0_1": "integer",
        "action_pdesc_0_1": "How many people",
    }
    r = c.post("/a/new", data=form)
    check("agent create redirects", r.status_code == 302, str(r.status_code))
    aid = r.headers["Location"].rstrip("/").split("/")[-1]
    check("agent id shape", bool(agentapi.API_ID_RE.match(aid)), aid)

    r = c.get("/a/" + aid)
    page = r.data.decode("utf-8", "replace")
    check("agent page 200", r.status_code == 200 and "/mcp" in page, str(r.status_code))

    r = c.get("/a/%s/openapi.json" % aid)
    check("agent openapi 200", r.status_code == 200 and r.is_json, str(r.status_code))
    check("agent openapi paths", "book_table" in json.dumps(r.get_json()))

    r = c.get("/a/%s/manifest.json" % aid)
    check("agent manifest 200", r.status_code == 200 and "mcp_url" in r.get_json(),
          str(r.status_code))

    r = c.post("/a/%s/mcp" % aid,
               json={"jsonrpc": "2.0", "id": 1, "method": "tools/list"})
    check("agent mcp tools/list", r.status_code == 200 and
          r.get_json()["result"]["tools"][0]["name"] == "book_table",
          str(r.status_code))

    r = c.post("/a/%s/mcp" % aid,
               json={"jsonrpc": "2.0", "id": 2, "method": "tools/call",
                     "params": {"name": "book_table",
                               "arguments": {"name": "Jane", "party_size": 4}}})
    body = r.get_json()
    first = json.loads(body["result"]["content"][0]["text"])
    check("agent mcp gated -> approval_required",
          r.status_code == 200 and first.get("approval_required") is True
          and first.get("approval_token"), str(body)[:160])
    mcp_token = first["approval_token"]
    r = c.post("/a/%s/mcp" % aid,
               json={"jsonrpc": "2.0", "id": 3, "method": "tools/call",
                     "params": {"name": "book_table",
                               "arguments": {"approval_token": mcp_token,
                                             "name": "Jane", "party_size": 4}}})
    body = r.get_json()
    check("agent mcp confirm executes",
          r.status_code == 200 and not body["result"]["isError"] and
          "book.example.com" in body["result"]["content"][0]["text"],
          str(body)[:200])
    r = c.post("/a/%s/mcp" % aid,
               json={"jsonrpc": "2.0", "id": 4, "method": "tools/call",
                     "params": {"name": "book_table",
                               "arguments": {"approval_token": mcp_token,
                                             "name": "Jane"}}})
    body = r.get_json()
    check("agent mcp token single-use",
          body["result"]["isError"] and
          "approval token" in body["result"]["content"][0]["text"].lower(),
          str(body)[:160])

    r = c.post("/a/%s/actions/book_table" % aid, json={"name": "Jane"})
    first = r.get_json()
    check("agent rest action gated -> approval_required",
          r.status_code == 200 and first.get("approval_required") is True
          and first.get("approval_token"), str(r.status_code))
    r = c.post("/a/%s/actions/book_table" % aid,
               json={"approval_token": first["approval_token"]})
    check("agent rest action confirm executes",
          r.status_code == 200 and "handoff_url" in r.get_json(), str(r.status_code))

    r = c.post("/a/%s/actions/book_table" % aid, json={})
    check("agent rest action missing param", r.status_code == 400, str(r.status_code))

    r = c.get("/a/0123456789ab")
    check("agent page 404 on unknown id", r.status_code == 404, str(r.status_code))

    bad_form = dict(form)
    bad_form["action_name"] = "Bad Name!"
    r = c.post("/a/new", data=bad_form)
    check("agent create 400 on bad action", r.status_code == 400, str(r.status_code))

    # ---- Unamused Connector (aggregator) ----
    import urllib.request as urlreq

    rec2 = agentapi.load_record(webapp.DATA_DIR, aid)
    check("load_record finds created api",
          rec2 is not None and rec2["business"] == "Mario & Salvo's Pizzeria")

    check("load_record rejects bad id", agentapi.load_record(webapp.DATA_DIR, "zzz") is None)

    listed = agentapi.list_records(webapp.DATA_DIR)
    check("list_records includes business",
          any(s["business_id"] == aid for s in listed), str(len(listed)))

    found = agentapi.search_records(webapp.DATA_DIR, "mario")
    check("search_records matches name",
          any(s["business_id"] == aid for s in found))
    check("search_records empty on miss",
          agentapi.search_records(webapp.DATA_DIR, "zzzznothing") == [])
    check("search_records blank query lists all",
          len(agentapi.search_records(webapp.DATA_DIR, "")) == len(listed))

    det = agentapi.business_detail(rec2)
    check("business_detail hides contact email", "contact_email" not in det)
    check("business_detail has schemas + approval",
          det["actions"][0]["input_schema"]["properties"].get("name") is not None
          and det["actions"][0]["requires_approval"] is True)

    r = agentapi.aggregator_mcp_handle(
        webapp.DATA_DIR, {"jsonrpc": "2.0", "id": 1, "method": "initialize"})
    check("agg mcp initialize",
          r["result"]["serverInfo"]["name"] == "unamused-connector")
    r = agentapi.aggregator_mcp_handle(
        webapp.DATA_DIR, {"jsonrpc": "2.0", "id": 2, "method": "tools/list"})
    tools = r["result"]["tools"]
    check("agg mcp 3 tools",
          [t["name"] for t in tools] == ["search_businesses", "get_business", "call_action"],
          str([t["name"] for t in tools]))
    check("agg call_action destructiveHint",
          next(t for t in tools if t["name"] == "call_action")
          .get("annotations", {}).get("destructiveHint") is True)
    r = agentapi.aggregator_mcp_handle(
        webapp.DATA_DIR, {"jsonrpc": "2.0", "id": 3, "method": "tools/call",
                          "params": {"name": "search_businesses",
                                     "arguments": {"query": "mario"}}})
    check("agg mcp search", not r["result"].get("isError") and aid in r["result"]["content"][0]["text"])
    r = agentapi.aggregator_mcp_handle(
        webapp.DATA_DIR, {"jsonrpc": "2.0", "id": 4, "method": "tools/call",
                          "params": {"name": "get_business",
                                     "arguments": {"business_id": aid}}})
    check("agg mcp get_business",
          not r["result"].get("isError") and "book_table" in r["result"]["content"][0]["text"])
    r = agentapi.aggregator_mcp_handle(
        webapp.DATA_DIR, {"jsonrpc": "2.0", "id": 5, "method": "tools/call",
                          "params": {"name": "call_action",
                                     "arguments": {"business_id": aid,
                                                   "action_name": "book_table",
                                                   "params": {"name": "Jane", "party_size": 2}}}})
    first = json.loads(r["result"]["content"][0]["text"])
    check("agg mcp gated -> approval_required",
          first.get("approval_required") is True and first.get("approval_token"),
          str(r["result"])[:160])
    r = agentapi.aggregator_mcp_handle(
        webapp.DATA_DIR, {"jsonrpc": "2.0", "id": 6, "method": "tools/call",
                          "params": {"name": "call_action",
                                     "arguments": {"business_id": aid,
                                                   "action_name": "book_table",
                                                   "approval_token": first["approval_token"],
                                                   "params": {"name": "Jane", "party_size": 2}}}})
    check("agg mcp confirm executes",
          not r["result"].get("isError") and "book.example.com" in r["result"]["content"][0]["text"],
          str(r["result"])[:200])
    r = agentapi.aggregator_mcp_handle(
        webapp.DATA_DIR, {"jsonrpc": "2.0", "id": 7, "method": "tools/call",
                          "params": {"name": "get_business",
                                     "arguments": {"business_id": "0123456789ab"}}})
    check("agg mcp unknown business isError", r["result"].get("isError") is True)
    r = agentapi.aggregator_mcp_handle(
        webapp.DATA_DIR, {"jsonrpc": "2.0", "id": 8, "method": "tools/call",
                          "params": {"name": "nope", "arguments": {}}})
    check("agg mcp unknown tool", r["error"]["code"] == -32601)

    spec = agentapi.aggregator_openapi_spec("https://unamused.app")
    check("agg openapi paths",
          "/connector/businesses" in spec["paths"] and
          "/connector/actions/{business_id}/{action}" in spec["paths"])
    man = agentapi.aggregator_manifest("https://unamused.app")
    check("agg manifest endpoints",
          man["mcp_url"].endswith("/connector/mcp") and
          man["openapi_url"].endswith("/connector/openapi.json") and
          man["name"] == "Unamused")

    # redirect guard: hostile 302 to a private host must be blocked
    h = agentapi._PublicRedirectHandler()
    try:
        h.redirect_request(urlreq.Request("https://example.com/"), None,
                           302, "Found", {}, "http://localhost/evil")
        redir_blocked = False
    except Exception:
        redir_blocked = True
    check("redirect to private host blocked", redir_blocked)

    r = c.get("/connector")
    check("connector page 200",
          r.status_code == 200 and b"/connector/mcp" in r.data, str(r.status_code))
    r = c.get("/connector/openapi.json")
    check("connector openapi 200", r.status_code == 200 and r.is_json, str(r.status_code))
    r = c.get("/connector/manifest.json")
    mj = r.get_json()
    check("connector manifest 200",
          r.status_code == 200 and mj["mcp_url"].endswith("/connector/mcp"))
    r = c.get("/connector/businesses?q=mario")
    check("connector search route",
          r.status_code == 200 and any(b["business_id"] == aid for b in r.get_json()["businesses"]),
          str(r.status_code))
    r = c.get("/connector/businesses/" + aid)
    check("connector business route",
          r.status_code == 200 and r.get_json()["business_id"] == aid, str(r.status_code))
    r = c.get("/connector/businesses/0123456789ab")
    check("connector business 404", r.status_code == 404, str(r.status_code))
    r = c.post("/connector/mcp",
               json={"jsonrpc": "2.0", "id": 1, "method": "tools/list"})
    check("connector mcp tools/list",
          r.status_code == 200 and len(r.get_json()["result"]["tools"]) == 3,
          str(r.status_code))
    r = c.post("/connector/mcp",
               json={"jsonrpc": "2.0", "id": 2, "method": "tools/call",
                     "params": {"name": "call_action",
                               "arguments": {"business_id": aid,
                                             "action_name": "book_table",
                                             "params": {"name": "Jane"}}}})
    body = r.get_json()
    first = json.loads(body["result"]["content"][0]["text"])
    check("connector mcp gated -> approval_required",
          r.status_code == 200 and first.get("approval_required") is True
          and first.get("approval_token"), str(body)[:160])
    r = c.post("/connector/mcp",
               json={"jsonrpc": "2.0", "id": 3, "method": "tools/call",
                     "params": {"name": "call_action",
                               "arguments": {"business_id": aid,
                                             "action_name": "book_table",
                                             "approval_token": first["approval_token"],
                                             "params": {"name": "Jane"}}}})
    body = r.get_json()
    check("connector mcp confirm executes",
          r.status_code == 200 and not body["result"]["isError"] and
          "book.example.com" in body["result"]["content"][0]["text"],
          str(body)[:200])
    r = c.post("/connector/actions/%s/book_table" % aid, json={"name": "Jane"})
    first = r.get_json()
    check("connector rest gated -> approval_required",
          r.status_code == 200 and first.get("approval_required") is True
          and first.get("approval_token"), str(r.status_code))
    r = c.post("/connector/actions/%s/book_table" % aid,
               json={"approval_token": first["approval_token"]})
    check("connector rest confirm executes",
          r.status_code == 200 and "handoff_url" in r.get_json(), str(r.status_code))
    r = c.post("/connector/actions/%s/book_table" % aid, json={})
    check("connector rest action missing param", r.status_code == 400, str(r.status_code))
    r = c.post("/connector/actions/0123456789ab/book_table", json={"name": "Jane"})
    check("connector rest action unknown business", r.status_code == 404, str(r.status_code))

    # ---- Server-enforced approval: edge cases ----
    ok, res = agentapi.confirm_approval(webapp.DATA_DIR, "nope-not-a-token", aid)
    check("unknown approval token rejected",
          not ok and "unknown" in res.get("error", ""), str(res))

    ok, prep = agentapi.prepare_approval(webapp.DATA_DIR, rec2, "book_table",
                                         {"name": "Zed"})
    tok = prep["approval_token"]
    ppath = os.path.join(webapp.DATA_DIR, "approval-%s.json" % tok)
    with open(ppath) as f:
        pend = json.load(f)
    pend["expires_at"] = 1  # long ago
    with open(ppath, "w") as f:
        json.dump(pend, f)
    ok, res = agentapi.confirm_approval(webapp.DATA_DIR, tok, aid)
    check("expired approval token rejected",
          not ok and "expired" in res.get("error", ""), str(res))

    ok, prep2 = agentapi.prepare_approval(webapp.DATA_DIR, rec2, "book_table",
                                          {"name": "Zed"})
    ok, res = agentapi.confirm_approval(webapp.DATA_DIR, prep2["approval_token"],
                                        "0123456789ab")
    check("approval token bound to business",
          not ok and "match" in res.get("error", ""), str(res))

    ok, prep3 = agentapi.prepare_approval(webapp.DATA_DIR, rec2, "book_table",
                                          {"name": "Jane"})
    ok, res = agentapi.request_action(webapp.DATA_DIR, rec2, "book_table",
                                      {"name": "Mallory"},
                                      approval_token=prep3["approval_token"])
    check("confirm uses approved params, ignores caller params",
          ok and "Jane" in res.get("handoff_url", "")
          and "Mallory" not in res.get("handoff_url", ""), str(res))

    nogate = json.loads(json.dumps(good))
    nogate["requires_approval"] = False
    recng = {"id": "t2", "business": "Test Biz", "actions": [nogate]}
    ok, res = agentapi.request_action(webapp.DATA_DIR, recng, "book_visit",
                                      {"name": "Jane"})
    check("non-gated action executes immediately",
          ok and res.get("handoff_url", "").endswith("name=Jane"), str(res))

    # ---- Webhook signing ----
    wh_action = {"name": "ping_hook", "title": "Ping", "description": "Ping.",
                 "params": [{"name": "msg", "type": "string", "required": False,
                              "description": ""}],
                 "channel": {"type": "webhook", "url": "https://example.com/hook"},
                 "requires_approval": False}
    wh_rec = agentapi.build_record("Hook Biz", "https://example.com", [wh_action])
    check("build_record creates webhook_secret",
          bool(wh_rec.get("webhook_secret")) and len(wh_rec["webhook_secret"]) >= 32)
    wh_path = os.path.join(webapp.DATA_DIR, "agentapi-%s.json" % wh_rec["id"])
    with open(wh_path, "w") as f:
        json.dump(wh_rec, f)
    captured = {}
    real_opener = urlreq.build_opener
    real_is_public = agentapi.is_public_host

    class FakeResp:
        def read(self, n=-1):
            return b'{"ok":true}'

        def __enter__(self):
            return self

        def __exit__(self, *a):
            return False

    class FakeOpener:
        def open(self, req, timeout=None):
            captured["headers"] = {k.lower(): v for k, v in req.header_items()}
            captured["data"] = req.data
            return FakeResp()

    urlreq.build_opener = lambda *a, **k: FakeOpener()
    agentapi.is_public_host = lambda host: True
    try:
        ok, res = agentapi.execute_action(wh_rec, "ping_hook", {"msg": "hi"},
                                          data_dir=webapp.DATA_DIR)
    finally:
        urlreq.build_opener = real_opener
        agentapi.is_public_host = real_is_public
    import hmac as hmac_mod
    import hashlib as hashlib_mod
    import time as time_mod
    sig = captured["headers"].get("x-unamused-signature", "")
    ts = captured["headers"].get("x-unamused-timestamp", "")
    idem_h = captured["headers"].get("x-unamused-idempotency-key", "")
    expect = hmac_mod.new(wh_rec["webhook_secret"].encode(),
                          ts.encode() + b"." + captured["data"],
                          hashlib_mod.sha256).hexdigest()
    check("webhook signature valid",
          ok and sig == "t=%s,v1=%s" % (ts, expect), sig[:48])
    check("webhook timestamp fresh",
          ts.isdigit() and abs(time_mod.time() - int(ts)) < 120, ts)
    check("webhook idempotency key in header + body",
          bool(idem_h) and json.loads(captured["data"])["idempotency_key"] == idem_h)
    check("webhook result marked signed", res.get("signed") is True)

    nosecret = {"id": agentapi.new_api_id(), "business": "Old Biz",
                "actions": [wh_action], "created_at": "x", "version": 1}
    nspath = os.path.join(webapp.DATA_DIR, "agentapi-%s.json" % nosecret["id"])
    with open(nspath, "w") as f:
        json.dump(nosecret, f)
    urlreq.build_opener = lambda *a, **k: FakeOpener()
    agentapi.is_public_host = lambda host: True
    try:
        agentapi.execute_action(nosecret, "ping_hook", {},
                                data_dir=webapp.DATA_DIR)
    finally:
        urlreq.build_opener = real_opener
        agentapi.is_public_host = real_is_public
    with open(nspath) as f:
        backfilled = json.load(f)
    check("webhook_secret backfilled for old records",
          bool(backfilled.get("webhook_secret")))

    # ---- Seed demos ----
    agentapi.ensure_seed_data(webapp.DATA_DIR)
    demos = [s for s in agentapi.list_records(webapp.DATA_DIR) if s.get("demo")]
    check("3 seed demos present", len(demos) == 3, str(len(demos)))
    check("seed demos flagged demo",
          all(d.get("demo") is True for d in demos) and
          all("(demo)" in d.get("business", "") for d in demos))
    n_before = len([f for f in os.listdir(webapp.DATA_DIR)
                    if f.startswith("agentapi-")])
    agentapi.ensure_seed_data(webapp.DATA_DIR)
    n_after = len([f for f in os.listdir(webapp.DATA_DIR)
                   if f.startswith("agentapi-")])
    check("seed idempotent", n_before == n_after,
          "%d -> %d" % (n_before, n_after))
    check("seed searchable",
          any(s["business_id"] == "deadbeef0001"
              for s in agentapi.search_records(webapp.DATA_DIR, "dental")))
    r = c.get("/connector/businesses")
    check("connector lists seed demos",
          r.status_code == 200 and
          sum(1 for b in r.get_json()["businesses"] if b.get("demo")) == 3)
    r = c.post("/connector/actions/deadbeef0001/request_quote",
               json={"name": "Test", "treatment": "cleaning"})
    check("demo link action executes",
          r.status_code == 200 and
          "example.com/sunny-smiles/quote" in r.get_json().get("handoff_url", ""),
          str(r.status_code))
    r = c.post("/connector/actions/deadbeef0001/book_appointment",
               json={"name": "Test", "phone_or_email": "x@y.z"})
    check("demo gated action needs approval (no network)",
          r.status_code == 200 and r.get_json().get("approval_required") is True,
          str(r.status_code))

    # ---- Badge embed page ----
    r = c.get("/badge")
    check("badge page 200",
          r.status_code == 200 and b"badge.svg" in r.data, str(r.status_code))
    check("badge page has copy snippet",
          b"embed snippet" in r.data and b"copy-btn" in r.data)
    r = c.get("/")
    check("footer links badge page", b'href="/badge"' in r.data)

    # ---- Analytics (first-party server-side counters) ----
    import datetime as _dt
    today = _dt.datetime.now(_dt.timezone.utc).strftime("%Y-%m-%d")
    afile = os.path.join(webapp.DATA_DIR, "analytics.json")

    def acounts():
        try:
            with open(afile) as f:
                return json.load(f)
        except (OSError, ValueError):
            return {}

    before = acounts().get("%s|badge_hit" % today, 0)
    r = c.get("/badge.svg", headers={"Referer": "https://shopexample.com/p"})
    check("badge.svg 200 svg",
          r.status_code == 200 and b"<svg" in r.data, str(r.status_code))
    after = acounts()
    check("badge_hit counted",
          after.get("%s|badge_hit" % today, 0) == before + 1)
    check("badge referer host counted",
          after.get("%s|ref|shopexample.com" % today, 0) >= 1)
    r = c.get("/static/badge.svg")
    check("static badge still served", r.status_code == 200)

    b_before = acounts().get("%s|badge_page" % today, 0)
    c.get("/badge")
    check("badge_page counted",
          acounts().get("%s|badge_page" % today, 0) == b_before + 1)

    k_before = acounts().get("%s|connector_call" % today, 0)
    c.get("/connector/businesses")
    check("connector_call counted on businesses",
          acounts().get("%s|connector_call" % today, 0) == k_before + 1)

    a_before = acounts().get("%s|audit_run" % today, 0)
    r = c.post("/audit", data={"url": "https://example.com"})
    if r.status_code in (301, 302, 303):
        check("audit_run counted",
              acounts().get("%s|audit_run" % today, 0) == a_before + 1)
        rid2 = r.headers["Location"].rsplit("/", 1)[-1]
        v_before = acounts().get("%s|report_view" % today, 0)
        c.get("/r/" + rid2)
        check("report_view counted",
              acounts().get("%s|report_view" % today, 0) == v_before + 1)

    r = c.get("/stats")
    sj = r.get_json()
    check("stats 200 with totals",
          r.status_code == 200 and "totals" in sj and "by_day" in sj
          and sj["totals"].get("badge_hit", 0) >= 1, str(r.status_code))
    check("stats notes no-tracking",
          "No cookies" in sj.get("note", ""))
    r = c.get("/")
    check("footer privacy note", b"No cookies" in r.data)

    with open(afile, "w") as f:
        f.write("not json{{{")
    r = c.get("/badge.svg")
    check("analytics never breaks requests on corrupt file",
          r.status_code == 200, str(r.status_code))

    print("\n%d failures" % len(fails))
    sys.exit(1 if fails else 0)


if __name__ == "__main__":
    main()
